# Generated by Django 3.1.7 on 2021-03-26 20:10

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('faculty_email', models.CharField(max_length=50)),
                ('faculty_phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('date_of_birth', models.DateField(help_text='optional')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('graduated_date', models.DateField(verbose_name='graduated_date')),
                ('year_as_faculty', models.CharField(choices=[('BD', 'Board'), ('MT', 'Mentor'), ('TT', 'Tutor'), ('SC', 'Scholarch'), ('ST', 'Staff')], default='TT', max_length=2)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
