# Generated by Django 3.1.7 on 2021-03-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'faculty'},
        ),
    ]
