# Generated by Django 3.1.7 on 2021-03-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20210326_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='year_as_faculty',
            new_name='faculty_position',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='optional'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='graduated_date',
            field=models.DateField(blank=True, verbose_name='graduated_date'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='start_date'),
        ),
    ]
