# Generated by Django 3.1.7 on 2021-03-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_number', models.CharField(blank=True, max_length=100, null=True)),
                ('course_start_date', models.DateField(blank=True, null=True, verbose_name='course_start_date')),
                ('course_end_date', models.DateField(blank=True, null=True, verbose_name='course_end_date')),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
    ]
